Services WIP {
    "com.bilibili" {
        playlists
        subscribes
        user-0 {
            history
            uploads
        }
        user-1 {
            history
            uploads
        }
    }
    "com.nmbxd1" {
        cookies
        subscribes
        posts
    }

    "com.bilibili" --> "com.nmbxd1" {
        style.opacity: 0
    }

    "com.163.music" {
        playlists
        subscribes
    } 
    "jp.nicovideo" {
        history
        playlists
        subscribes
    }
    "fm.libre" {
        history
        current
    }

    "com.163.music" --> "jp.nicovideo" {
        style.opacity: 0
    }
    "jp.nicovideo" --> "fm.libre" {
        style.opacity: 0
    }

    "com.tencent.qq" {
        chat history
        contacts
    }
    "com.tencent.mm" {
        chat history
        contacts
    }
    "cn.feishu" {
        chat history
        contacts
    }
    "org.telegram" {
        chat history
        contacts
    }
    "com.discord" {
        chat history
        contacts
    }
    "com.fedibird.matrix" {
        chat history
        contacts
    }

    "com.tencent.qq" --> "com.tencent.mm" {
        style.opacity: 0
    }
    "com.tencent.mm" --> "cn.feishu" {
        style.opacity: 0
    }
    "org.telegram" --> "com.discord" {
        style.opacity: 0
    }
    "com.discord" --> "com.fedibird.matrix" {
        style.opacity: 0
    }

    "com.taobao"
    "com.jd"
    "com.meituan"
    "com.goofish"
    "internal.me.shopping"

    "com.taobao" --> "com.jd" {
        style.opacity: 0
    }
    "com.jd" --> "com.meituan" {
        style.opacity: 0
    }
    "com.goofish" --> "internal.me.shopping" {
        style.opacity: 0
    }

    "org.disroot.mail"
    "me.proton.mail"
    "internal.work-0.mail"

    "org.disroot.mail" --> "me.proton.mail" {
        style.opacity: 0
    }
    "me.proton.mail" --> "internal.work-0.mail" {
        style.opacity: 0
    }

    "com.github"
    "org.codeberg"
    "internal.work-0.git"
    "internal.work-1.git"

    "com.github" --> "org.codeberg" {
        style.opacity: 0
    }
    "internal.work-0.git" --> "internal.work-1.git" {
        style.opacity: 0
    }

    "org.postimages"
    "internal.me.photos"
    "com.google.gemini"

    "org.postimages" --> "internal.me.photos" {
        style.opacity: 0
    }
    "internal.me.photos" --> "com.google.gemini" {
        style.opacity: 0
    }

    "com.rayark.cytus2" {
        songlist
        play record
    }
    "com.rayark.deemo" {
        songlist
        play record
    }
    "com.bang-dream" {
        songlist
        play record
    }
    "jp.sega.pjsekai" {
        songlist
        play record
    }
    "com.PigeonGames.Phigros" {
        songlist
        play record
    }
    "net.peropero.musedash" {
        songlist
        play record
    }
    "net.hajimeli.vividstasis" {
        songlist
        play record
    }
    "xyz.euclidia"

    "com.rayark.cytus2" --> "com.rayark.deemo" {
        style.opacity: 0
    }
    "com.rayark.deemo" --> "com.bang-dream" {
        style.opacity: 0
    }
    "jp.sega.pjsekai" --> "com.PigeonGames.Phigros" {
        style.opacity: 0
    }
    "com.PigeonGames.Phigros" --> "net.peropero.musedash" {
        style.opacity: 0
    }
    "net.hajimeli.vividstasis" --> "xyz.euclidia" {
        style.opacity: 0
    }

}

Services {
    "com.163.music" {
        history
    } 
    "internal.me.payments" {
        BOC
        ICBC
        Paypal
        AliPay
        WeChat
    }
    "cc.fanbox.mea"
    "cn.arcaea.wiki" {
        shape: cloud
    }
    "com.lowiro.arcaea" {
        play record
        songlist
    }
    "com.hempuli.baba"
    "internal.game.theendlessempty" {
        footage
        saves
    }
    "org.terraria" {
        worlds
        players
        footage
    }
    "net.minecraft" {
        players
        footage
        worlds
    }
    "internal.me.human" {
        weight
        sleep
        step
        heart rate
    }
    "internal.device" {
        scale
        band
    }
    "internal.me.text"

    "com.youtube" {
        history
        playlists
        subscribes
        uploads
    }
    "com.google.mail"

    "internal.me.human".weight --> "internal.device".scale
    "internal.me.human".sleep --> "internal.device".band
    "internal.me.human".step --> "internal.device".band
    "internal.me.human".heart rate --> "internal.device".band
    "com.lowiro.arcaea".songlist --> "cn.arcaea.wiki"
}

DEL: Data Export Layer {
    web-scrobbler {
        link: https://github.com/web-scrobbler/web-scrobbler
        shape: package
    }
    Accounting {
        shape: person
    }
    Download Fanbox {
        shape: person
    }
    Y-Offline {
        shape: person
    }
    arcaea-database-maintainer {
        shape: package
    }
    bili-uploader {
        shape: person
    }
    duplicity {
        shape: package
    }
    Export Scale Image {
        shape: person
    }
    Sync On Edit (Git)
    Google Takeout {
        shape: person
        tooltip: once per 2 months, manually download
        youtube
        mail
    }
}

Data {
    "fm.libre" {
        link: https://libre.fm
        shape: cloud
    }
    "beancount" {
        # this shape means files 
        shape: document
    }
    "internal.node.lexikos.filesystem".fanbox { 
        shape: stored_data
    }
    "y_offline DB" {
        shape: cylinder
    }
    "com.bilibili.user-1" {
        shape: cloud
    }
    "com.github" {
        shape: cloud
        ArcaeaSongDatabase {
            link: https://github.com/CuSO4Deposit/ArcaeaSongDatabase
        }
        logseq
    }
    "internal.work-1.JuiceFS" {
        duplicity
    }
    "internal.device.phone-2.filesystem" {
        scale info pictures
    }
    "internal.node.lexikos.filesystem" {
        ArcaeaSongDatabase
    }

    "internal.node.lexikos.filesystem".ArcaeaSongDatabase --> "com.github".ArcaeaSongDatabase : {
        label: git push
    }
    "internal.node.laborari.filesystem".Takeout {
        youtube
        mail
    }
}

DAL: Data Access Layer {
    Beancount {
        link: https://github.com/beancount/beancount
        shape: package
    }
    Y-Offline {
        shape: package
    }
    LogSeq {
        link: https://logseq.com
        shape: package
    }
}

Applications {
    Fava {
        link: https://github.com/beancount/fava
        shape: cloud
    }
    Y-Offline CLI {
        shape: package
    }
    LogSeq {
        shape: package
    }
}

Services WIP --> Services {
    style.opacity: 0
}

Services."com.163.music".history --> DEL.web-scrobbler
DEL.web-scrobbler --> Data."fm.libre"

Services."internal.me.payments" --> DEL.Accounting
DEL.Accounting --> Data."beancount"
Data."beancount" --> DAL.Beancount
DAL.Beancount --> Applications.Fava

Services."cc.fanbox.mea" --> DEL.Download Fanbox
DEL.Download Fanbox --> Data."internal.node.lexikos.filesystem".fanbox

Services."com.lowiro.arcaea".play record --> DEL.Y-Offline
DEL.Y-Offline --> Data."y_offline DB"
Data."y_offline DB" --> DAL.Y-Offline
Data."internal.node.lexikos.filesystem".ArcaeaSongDatabase --> DAL.Y-Offline
DAL.Y-Offline --> Applications.Y-Offline CLI

Services."cn.arcaea.wiki" --> DEL.arcaea-database-maintainer
DEL.arcaea-database-maintainer --> Data."internal.node.lexikos.filesystem".ArcaeaSongDatabase : {
    label: manually run script
}

Services."com.youtube" --> DEL.Google Takeout.youtube
DEL.Google Takeout.youtube --> Data."internal.node.laborari.filesystem".Takeout.youtube

Services."com.google.mail" --> DEL.Google Takeout.mail
DEL.Google Takeout.mail --> Data."internal.node.laborari.filesystem".Takeout.mail

Services."org.terraria".footage --> DEL.bili-uploader
Services."net.minecraft".footage --> DEL.bili-uploader
Services."com.hempuli.baba" --> DEL.bili-uploader
Services."internal.game.theendlessempty".footage --> DEL.bili-uploader
DEL.bili-uploader --> Data."com.bilibili.user-1"

Services."net.minecraft".worlds --> DEL.duplicity
DEL.duplicity --> Data."internal.work-1.JuiceFS".duplicity

Services."internal.device".scale --> DEL."Export Scale Image"
DEL."Export Scale Image" --> Data."internal.device.phone-2.filesystem".scale info pictures

Services."internal.me.text" --> DEL."Sync On Edit (Git)"
DEL."Sync On Edit (Git)" --> Data."com.github".logseq
Data."com.github".logseq --> DAL.LogSeq
DAL.LogSeq --> Applications.LogSeq
