Services WIP {
    "com.nmbxd1" {
        cookies
        subscribes
        posts
    }

    "com.163.music" {
        playlists
        subscribes
    }
    "jp.nicovideo" {
        history
        playlists
        subscribes
    }

    "com.163.music" --> "jp.nicovideo" {
        style.opacity: 0
    }

    "com.tencent.qq" {
        chat history
        contacts
    }
    "com.tencent.mm" {
        chat history
        contacts
    }
    "cn.feishu" {
        chat history
        contacts
    }
    "org.telegram" {
        chat history
        contacts
    }
    "com.discord" {
        chat history
        contacts
    }
    "com.fedibird.matrix" {
        chat history
        contacts
    }

    "com.tencent.qq" --> "com.tencent.mm" {
        style.opacity: 0
    }
    "com.tencent.mm" --> "cn.feishu" {
        style.opacity: 0
    }
    "org.telegram" --> "com.discord" {
        style.opacity: 0
    }
    "com.discord" --> "com.fedibird.matrix" {
        style.opacity: 0
    }

    "com.taobao"
    "com.jd"
    "com.meituan"
    "com.goofish"
    "invalid.me.shopping"

    "com.taobao" --> "com.jd" {
        style.opacity: 0
    }
    "com.jd" --> "com.meituan" {
        style.opacity: 0
    }
    "com.goofish" --> "invalid.me.shopping" {
        style.opacity: 0
    }

    "org.disroot.mail"
    "me.proton.mail"
    "invalid.work-0.mail"

    "org.disroot.mail" --> "me.proton.mail" {
        style.opacity: 0
    }
    "me.proton.mail" --> "invalid.work-0.mail" {
        style.opacity: 0
    }

    "invalid.work-1.git"

    "org.postimages"

    "org.postimages" --> "invalid.me.photos" {
        style.opacity: 0
    }

    "com.rayark.cytus2" {
        songlist
        play record
    }
    "com.rayark.deemo" {
        songlist
        play record
    }
    "com.bang-dream" {
        songlist
        play record
    }
    "jp.sega.pjsekai" {
        songlist
        play record
    }
    "com.PigeonGames.Phigros" {
        songlist
        play record
    }
    "net.peropero.musedash" {
        songlist
        play record
    }
    "net.hajimeli.vividstasis" {
        songlist
        play record
    }
    "xyz.euclidia"

    "com.rayark.cytus2" --> "com.rayark.deemo" {
        style.opacity: 0
    }
    "com.rayark.deemo" --> "com.bang-dream" {
        style.opacity: 0
    }
    "jp.sega.pjsekai" --> "com.PigeonGames.Phigros" {
        style.opacity: 0
    }
    "com.PigeonGames.Phigros" --> "net.peropero.musedash" {
        style.opacity: 0
    }
    "net.hajimeli.vividstasis" --> "xyz.euclidia" {
        style.opacity: 0
    }

}

Services {
    "com.bilibili" {
        playlists
        subscribes
        history
        user-1 {
            uploads metadata
        }
    }
    "fm.libre" {
        history
        current
    }
    "com.github" {
        user-0
        user-1
    }
    "org.codeberg"
    "invalid.work-0.git"
    "com.163.music" {
        history
    }
    "invalid.me.payments" {
        BOC
        ICBC
        Paypal
        AliPay
        WeChat
    }
    "cc.fanbox.mea": "cc.fanbox.mea (x2)" {
        shape: stored_data
    }
    "cn.arcaea.wiki" {
        shape: cloud
    }
    "com.lowiro.arcaea" {
        play record
        songlist
    }
    "com.hempuli.baba"
    "invalid.game.theendlessempty" {
        footage
        saves {
            shape: stored_data
        }
    }
    "org.terraria" {
        footage
        worlds: "worlds (x2)" {
            shape: stored_data
        }
        players: "players (x2)" {
            shape: stored_data
        }
    }
    "net.minecraft" {
        players: "players (x2)" {
            shape: stored_data
        }
        footage
        worlds: "worlds (x2)" {
            shape: stored_data
        }
    }
    "invalid.me.human" {
        weight
        sleep
        step
        heart rate
    }
    "invalid.device" {
        scale
        band
    }
    "invalid.me.text": "invalid.me.text (x2)" {
        shape: stored_data
    }

    "com.youtube" {
        history
        playlists
        subscribes
        uploads
    }
    "com.google.mail"

    "invalid.me.human".weight --> "invalid.device".scale
    "invalid.me.human".sleep --> "invalid.device".band
    "invalid.me.human".step --> "invalid.device".band
    "invalid.me.human".heart rate --> "invalid.device".band
    "com.lowiro.arcaea".songlist --> "cn.arcaea.wiki"
    "invalid.me.photos"
}

DEL: Data Export Layer {
    web-scrobbler {
        link: https://github.com/web-scrobbler/web-scrobbler
        shape: package
    }
    Accounting {
        shape: person
    }
    Download Fanbox {
        shape: person
    }
    Y-Offline {
        shape: person
    }
    arcaea-database-maintainer {
        shape: person
        arcaea-database-maintainer {
            shape: package
        }
    }
    bili-uploader {
        shape: person
    }
    duplicity {
        shape: package
        link: https://duplicity.gitlab.io/
        lexikos
        proximo
    }
    ghorg {
        shape: package
        link: https://github.com/gabrie30/ghorg
    }
    Export Scale Image {
        shape: person
    }
    Sync On Edit (Git)
    Google Takeout {
        shape: person
        tooltip: once per 2 months, manually download
        youtube
        mail
    }
    Export to Photos {
        shape: person
    }
}

Data {
    "fm.libre" {
        link: https://libre.fm
        shape: cloud
    }
    "beancount": "beancount (x2)" {
        shape: stored_data
    }
    "invalid.node.lexikos.filesystem" {
        fanbox: "fanbox (x2)" {
            shape: stored_data
        }
        "Y-Offline DB" {
            shape: cylinder
        }
    }
    "com.bilibili.user-1" {
        shape: cloud
        uploads {
            shape: stored_data
        }
    }
    "com.github" {
        shape: cloud
        ArcaeaSongDatabase: "ArcaeaSongDatabase (x2)" {
            link: https://github.com/CuSO4Deposit/ArcaeaSongDatabase
        }
        logseq: "logseq (x2)"
        beancount: "beancount (x2)"
    }
    "invalid.work-1.JuiceFS" {
        duplicity {
            shape: stored_data
        }
    }
    "invalid.device.phone-2.filesystem" {
        scale info pictures
    }
    "invalid.node.proximo.filesystem" {
        ghorg {
            shape: stored_data
        }
        digikam {
            shape: stored_data
        }
        piwigo {
            shape: stored_data
        } 
    }
    "invalid.node.lexikos.filesystem" {
        ArcaeaSongDatabase: "ArcaeaSongDatabase (x2)"
    }

    "invalid.node.lexikos.filesystem".ArcaeaSongDatabase --> "com.github".ArcaeaSongDatabase : {
        label: git push
    }
    "beancount" --> "com.github".beancount : {
        label: git push
    }
    "invalid.node.laborari.filesystem".Takeout {
        youtube {
            shape: stored_data
        }
        mail {
            shape: stored_data
        }
    }
}

DAL: Data Access Layer {
    Beancount {
        link: https://github.com/beancount/beancount
        shape: package
    }
    Y-Offline {
        shape: package
    }
    LogSeq {
        link: https://logseq.com
        shape: package
    }
    duplicity {
        shape: package
        link: https://duplicity.gitlab.io/
    }
    cgit {
        shape: package
        link: https://git.zx2c4.com/cgit/about/
    }
    digikam {
        shape: package
    }
    piwigo {
        shape: package
    }
}

Applications {
    Fava Web {
        link: http://fava.internal
        shape: cloud
    }
    Y-Offline {
        link: https://y-offline.depoze.xyz
        shape: package

    }
    LogSeq {
        shape: package
    }
    "internal.git-ro" {
        link: http://git-ro.internal
        shape: cloud
    }
    "invalid.domain-1.piwigo" {
        shape: cloud
    }
}

Services WIP --> Services {
    style.opacity: 0
}

Services."com.163.music".history --> DEL.web-scrobbler
DEL.web-scrobbler --> Data."fm.libre"

Services."invalid.me.payments" --> DEL.Accounting
DEL.Accounting --> Data."beancount"
Data."beancount" --> DAL.Beancount
DAL.Beancount --> Applications.Fava Web

Services."cc.fanbox.mea" --> DEL.Download Fanbox
DEL.Download Fanbox --> Data."invalid.node.lexikos.filesystem".fanbox
DEL.Download Fanbox --> Data."invalid.work-1.JuiceFS".duplicity : {
    label: duplicity
}

Services."com.lowiro.arcaea".play record --> DEL.Y-Offline
DEL.Y-Offline --> Data."invalid.node.lexikos.filesystem".Y-Offline DB
Data."invalid.node.lexikos.filesystem"."Y-Offline DB" --> DAL.Y-Offline
Data."invalid.node.lexikos.filesystem".ArcaeaSongDatabase --> DAL.Y-Offline
DAL.Y-Offline --> Applications.Y-Offline

Services."cn.arcaea.wiki" --> DEL.arcaea-database-maintainer
DEL.arcaea-database-maintainer --> Data."invalid.node.lexikos.filesystem".ArcaeaSongDatabase : {
    label: manually run script
}

Services."com.youtube" --> DEL.Google Takeout.youtube
DEL.Google Takeout.youtube --> Data."invalid.node.laborari.filesystem".Takeout.youtube

Services."com.google.mail" --> DEL.Google Takeout.mail
DEL.Google Takeout.mail --> Data."invalid.node.laborari.filesystem".Takeout.mail

Services."org.terraria".footage --> DEL.bili-uploader
Services."net.minecraft".footage --> DEL.bili-uploader
Services."com.hempuli.baba" --> DEL.bili-uploader
Services."invalid.game.theendlessempty".footage --> DEL.bili-uploader
DEL.bili-uploader --> Data."com.bilibili.user-1".uploads

Services."net.minecraft".players --> DEL.duplicity.lexikos
Services."org.terraria".worlds --> DEL.duplicity.lexikos
Services."org.terraria".players --> DEL.duplicity.lexikos
DEL.duplicity.lexikos --> Data."invalid.work-1.JuiceFS".duplicity

Services."net.minecraft".worlds --> DEL.duplicity.proximo
DEL.duplicity.proximo --> Data."invalid.work-1.JuiceFS".duplicity
Data."invalid.work-1.JuiceFS".duplicity --> DAL.duplicity

Services."com.github" --> DEL.ghorg
Services."invalid.work-0.git" --> DEL.ghorg
DEL.ghorg --> Data."invalid.node.proximo.filesystem".ghorg
Data."invalid.node.proximo.filesystem".ghorg --> DAL.cgit
DAL.cgit --> Applications."internal.git-ro"

Services."invalid.device".scale --> DEL."Export Scale Image"
DEL."Export Scale Image" --> Data."invalid.device.phone-2.filesystem".scale info pictures

Services."invalid.me.text" --> DEL."Sync On Edit (Git)"
DEL."Sync On Edit (Git)" --> Data."com.github".logseq
Data."com.github".logseq --> DAL.LogSeq
DAL.LogSeq --> Applications.LogSeq

Services."invalid.me.photos" --> DEL."Export Photos"
DEL."Export Photos" --> Data."invalid.node.proximo.filesystem".digikam
Data."invalid.node.proximo.filesystem".digikam --> Data."invalid.node.proximo.filesystem".piwigo
Data."invalid.node.proximo.filesystem".digikam --> DAL.digikam
Data."invalid.node.proximo.filesystem".piwigo --> DAL.piwigo
DAL.piwigo --> Applications."invalid.domain-1.piwigo"
